{{- if or .Values.masterkey.value (not (and .Values.masterkey.existingSecret.key .Values.masterkey.existingSecret.name)) }}
{{ $masterkey := (.Values.masterkey.value | default (randAlphaNum 17)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-masterkey
data:
  masterkey: {{ $masterkey | b64enc }}
type: Opaque
{{- end }}