apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "litellm.fullname" . }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "litellm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-litellm.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "litellm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "litellm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.proxy_config_persistence.enabled .Values.proxy_config_persistence.sharedVolumeExistingClaim }}
      initContainers:
        # TODO: init container to create config.yaml if not exists
        - name: ensure-config-file-exists
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: bash:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - bash
          - -c
          - |
            [[ -d /mnt/share/litellm ]] || mkdir -p -m 777 /mnt/share/litellm
            [[ -s /mnt/share/litellm/config.yaml ]] && exit 0
            echo "now creating config file using defined configmap..."
            echo ""
            cat /opt/ref/litellm/config.yaml > /mnt/share/litellm/config.yaml
            echo "config file created successfully."
          volumeMounts:
          - name: litellm-config-volume
            mountPath: /mnt/share/
          - name: litellm-config
            mountPath: /opt/ref/litellm/
      {{- end }}
      containers:
        - name: {{ include "litellm.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "main-%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST
              value: "{{ .Values.listen | default "0.0.0.0" }}"
            - name: PORT
              value: {{ .Values.service.port | quote}}
            {{- if .Values.db.deployStandalone }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "litellm.fullname" . }}-dbcredentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "litellm.fullname" . }}-dbcredentials
                  key: password
            - name: DATABASE_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DATABASE_NAME
              value: litellm
            {{- else if .Values.db.useExisting }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: {{ .Values.db.secret.usernameKey }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: {{ .Values.db.secret.passwordKey }}
            - name: DATABASE_HOST
              value: {{ .Values.db.endpoint }}
            - name: DATABASE_NAME
              value: {{ .Values.db.database }}
            - name: DATABASE_URL
              value: {{ .Values.db.url | quote }}
            {{- end }}
            {{- if and (not .Values.masterkey) (and .Values.masterkeyExistingSecret.key .Values.masterkeyExistingSecret.name) }}
            - name: PROXY_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.masterkeyExistingSecret.name }}
                  key: {{ .Values.masterkeyExistingSecret.key }}
            {{- else }}
            - name: PROXY_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "litellm.fullname" . }}-masterkey
                  key: masterkey
            {{- end }}
            {{- if .Values.redis.enabled }}
            {{- if .Values.redis.endpoint }}
            - name: REDIS_HOST
              value: {{ .Values.redis.endpoint | quote }}
            {{- else }}
            - name: REDIS_HOST
              value: {{ include "litellm.redis.serviceName" . }}
            {{- end }}
            - name: REDIS_PORT
              value: {{ include "litellm.redis.port" . | quote }}
            {{- if and .Values.redis.secret.name .Values.redis.secret.passwordKey }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.redis.secret.passwordKey }}
                  name: {{ .Values.redis.secret.name }}
            {{- end }}
            {{- if or .Values.redis.username (and .Values.redis.secret.name .Values.redis.secret.usernameKey) }}
            - name: REDIS_USER
              {{- if .Values.redis.username }}
              value: {{ .Values.redis.username }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.redis.secret.usernameKey }}
                  name: {{ .Values.redis.secret.name }}
              {{- end }}
            {{- end }}
            {{- if .Values.envVars }}
            {{- range $key, $val := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
          envFrom:
          {{- range .Values.environmentSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- range .Values.environmentConfigMaps }}
            - configMapRef:
                name: {{ . }}
          {{- end }}
          args:
            - --config
            {{- if and .Values.proxy_config_persistence.enabled .Values.proxy_config_persistence.sharedVolumeExistingClaim }}
            - /mnt/share/litellm/config.yaml
            {{- else }}
            - /etc/litellm/config.yaml
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          # Give the container time to start up.  Up to 5 minutes (10 * 30 seconds)
          startupProbe:
            httpGet:
              path: /health/readiness
              port: http
            failureThreshold: 30
            periodSeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if and .Values.proxy_config_persistence.enabled .Values.proxy_config_persistence.sharedVolumeExistingClaim }}
            - name: litellm-config-volume
              mountPath: /mnt/share/
            {{- else }}
            - name: litellm-config
              mountPath: /etc/litellm/
            {{- end }}
          {{ if .Values.securityContext.readOnlyRootFilesystem }}
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /.cache
            - name: npm
              mountPath: /.npm
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{ if .Values.securityContext.readOnlyRootFilesystem }}
        - name: tmp
          emptyDir:
            sizeLimit: 500Mi
        - name: cache
          emptyDir:
            sizeLimit: 500Mi
        - name: npm
          emptyDir:
            sizeLimit: 500Mi
        {{- end }}
        {{- if and .Values.proxy_config_persistence.enabled .Values.proxy_config_persistence.sharedVolumeExistingClaim }}
        - name: litellm-config-volume
          persistentVolumeClaim:
            claimName: {{ .Values.proxy_config_persistence.sharedVolumeExistingClaim | quote }}
        - name: litellm-config
          configMap:
            name: {{ include "litellm.fullname" . }}-config
            items:
              - key: "config.yaml"
                path: "config.yaml"
        {{- else }}
        - name: litellm-config
          configMap:
            name: {{ include "litellm.fullname" . }}-config
            items:
              - key: "config.yaml"
                path: "config.yaml"
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
