{{- if or .Values.masterkey (not (and .Values.masterkeyExistingSecret.key .Values.masterkeyExistingSecret.name)) }}
{{ $masterkey := (.Values.masterkey | default (randAlphaNum 17)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-masterkey
data:
  masterkey: {{ $masterkey | b64enc }}
type: Opaque
{{- end }}